Install github version of lasagne in runtime requirements
When the pypi version of lasagne (v0.1) is installed, we get this error:

```
$ python -c 'import wbia_cnn'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Lasagne failed to import
cannot import name 'downsample' from 'theano.tensor.signal' (/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/theano/tensor/signal/__init__.py)
Traceback (most recent call last):
  File "/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/wbia_cnn/__LASAGNE__.py", line 9, in <module>
    from lasagne import *  # NOQA
  File "/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name 'downsample' from 'theano.tensor.signal' (/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/theano/tensor/signal/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/wbia_cnn/__init__.py", line 9, in <module>
    from wbia_cnn import __LASAGNE__
  File "/home/karen/src/wildbook/wbia-plugin-cnn/wheelhouse/py3/lib/python3.8/site-packages/wbia_cnn/__LASAGNE__.py", line 13, in <module>
    print('theano.__version__ = %r' % (theano.__version__,))
AttributeError: module 'wbia_cnn.__THEANO__' has no attribute '__version__'
```

It seems that lasagne v0.1 is not compatible with theano >0.7.  There's
no newer versions on pypi for lasagne, but there's active development on
github, so the only thing we can do is to install the github version of
lasagne.

Also setup.py `extras_require` doesn't accept "git+..." as valid
requirements:

```
error in wbia_cnn setup command: 'extras_require' must be a
dictionary whose values are strings or lists of strings containing
valid project/version requirement specifiers.
```

So adjust `parse_requirements` in `setup.py` to remove the git urls.