Add missing "import sys" in setup.py
```
    File "setup.py", line 127, in <module>
      install_requires = parse_requirements('requirements/runtime.txt')
    File "setup.py", line 120, in parse_requirements
      packages = list(gen_packages_items())
    File "setup.py", line 112, in gen_packages_items
      if not sys.version.startswith('3.4'):
  NameError: name 'sys' is not defined
  ----------------------------------------
ERROR: Command errored out with exit status 1: /virtualenv/env3/bin/python3 /virtualenv/env3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp6a1gk6lq Check the logs for full command output.
```