Rename wbia_cnn/_grave.py to wbia_cnn/_grave.txt
The file seems to contain command lines for running wbia_cnn not python
code and is causing the code style fixer brunette to fail:

```
brunette.................................................................Failed
- hook id: brunette
- exit code: 123
- files were modified by this hook

reformatted /home/karen/src/wildbook/wbia-plugin-cnn/broken/old_batch.py
...
reformatted /home/karen/src/wildbook/wbia-plugin-cnn/wbia_cnn/utils.py
All done! ✨ 🍰 ✨
14 files reformatted.
error: cannot format /home/karen/src/wildbook/wbia-plugin-cnn/broken/old_train.py: Cannot parse: 3:10: python -m ibeis_cnn --tf pz_patchmatch --db PZ_Master0 --colorspace='gray' --num-top=None --controlled=True --aliasexit
reformatted /home/karen/src/wildbook/wbia-plugin-cnn/test_theano.py
error: cannot format /home/karen/src/wildbook/wbia-plugin-cnn/wbia_cnn/_grave.py: Cannot parse: 3:4: OLD COMMAND LINE:
reformatted /home/karen/src/wildbook/wbia-plugin-cnn/wbia_cnn/_plugin_grabmodels.py
reformatted /home/karen/src/wildbook/wbia-plugin-cnn/broken/old_test.py
...
Oh no! 💥 💔 💥
12 files reformatted, 2 files failed to reformat.
```

Renaming the file should get brunette to ignore it.